ERROR:root:Exception occurred
Traceback (most recent call last):
  File "D:\Hackathon\Crasheye_backend\Test\new_try\generate_crash.py", line 92, in <module>
    generate_random_crash()
  File "D:\Hackathon\Crasheye_backend\Test\new_try\generate_crash.py", line 75, in generate_random_crash
    upload_crash_to_mongo(file,time_stamp,pl_sys,pl_node,pl_rel,pl_ver,pl_mach,pl_proc,svmem.percent,"FATAL",gpu_sql) # type: ignore
TypeError: upload_crash_to_mongo() takes 1 positional argument but 11 were given
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
DEBUG:pymongo.ocsp_support:OCSP response status: <OCSPResponseStatus.SUCCESSFUL: 0>
DEBUG:pymongo.ocsp_support:Verifying response
DEBUG:pymongo.ocsp_support:Responder is issuer
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Caching OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:Peer did not staple an OCSP response
DEBUG:pymongo.ocsp_support:Requesting OCSP data
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:Trying http://r3.o.lencr.org
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
DEBUG:pymongo.ocsp_support:Using cached OCSP response.
DEBUG:pymongo.ocsp_support:OCSP cert status: <OCSPCertStatus.GOOD: 0>
